[package]
name = "ip_reputation_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.0.17"
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }

