[package]
name = "ip_reputation_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "3.2.22"
tokio = { version = "1.0", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
dotenv = "0.15"
serde = "1.0"
serde_json = "1.0"
ipinfo = "3.0.0"